version: "3"
services:
  web:
    image: sabmark/dap70
    container_name: dap70
    hostname: sabmark.dap70
    networks:
      sabmark:
        ipv4_address: 172.23.0.5
    ports:
      - "80:80"
      - "443:443"
      - "41017:41017"
    volumes:
      - /Users/sabmark/Sites:/var/www
#      - /Volumes/Sabandal/Documents/Snapfrozen:/home/snapfrozen
      - ./config/vhost:/etc/apache2/sites-enabled
      - ./config/cron:/etc/cron.d
      - ./config/php/7.0/php.ini:/etc/php/7.0/apache2/php.ini
      - ./config/supervisor:/etc/supervisor/conf.docker
networks:
  sabmark:
    external:
      name: sabmark